spring:
  application:
   # name: product-service
   name: PRODUCT-SERV

server:
  port: 8083

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8082/eureka/
  instance:
    hostname: localhost